import numpy as np

print('first try int16')
values = (-128,-1,0,1,127)
data = np.array(values,dtype=np.int8)
print('int8=',data)
dataMin = int(np.min(data))
dataMax = int(np.max(data))
xp = (float(dataMin),float(dataMax))
fp = (0.0,255.0)
data = np.interp(data,xp,fp)
#print('dtype=',data.dtype,' data=',data)
data = data.astype(np.uint8)
print('uint8=',data)

print('\nnow try int16')
values = (-32768,-256,0,256,32767)
data = np.array(values,dtype=np.int16)
print('int16=',data)
dataMin = int(np.min(data))
dataMax = int(np.max(data))
xp = (float(dataMin),float(dataMax))
fp = (0.0,65535.0)
data = np.interp(data,xp,fp)
#print('dtype=',data.dtype,' data=',data)
data = data.astype(np.uint16)
print('uint16=',data)
dataMin = int(np.min(data))
dataMax = int(np.max(data))
xp = (float(dataMin),float(dataMax))
fp = (0.0,255.0)
data = np.interp(data,xp,fp)
#print('dtype=',data.dtype,' data=',data)
data = data.astype(np.uint8)
print('uint8=',data)

print('\nnow try int32')
values = (-2147483648,-65536,0,65536,2147483647)
#data = np.array(values,dtype=np.int32)
print('int32=',data)
dataMin = int(np.min(data))
dataMax = int(np.max(data))
xp = (float(dataMin),float(dataMax))
fp = (0.0,4294967295.0)
data = np.interp(data,xp,fp)
#print('dtype=',data.dtype,' data=',data)
data = data.astype(np.uint32)
print('uint32=',data)
dataMin = int(np.min(data))
dataMax = int(np.max(data))
xp = (float(dataMin),float(dataMax))
fp = (0.0,255.0)
data = np.interp(data,xp,fp)
#print('dtype=',data.dtype,' data=',data)
data = data.astype(np.uint8)
print('uint8=',data)

